stages:
- name: test_stage
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install
        npm test
- name: package_stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: deploy_stage
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
