stages:
- name: test_stage
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install
        npm test
- name: package_stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: repo/my-image:dev
      pushRemote: true
      registry: 127.0.0.1:34098
- name: deploy_stage
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
